@/home/fang/disk1/fang/IDL_sources/mpfit/gauss1p.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/gauss1.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/gauss2.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpchilim.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpchitest.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpcurvefit.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfit2dfun.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfit2dpeak.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfitellipse.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfitexpr.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfitfun.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfitpeak.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpfit.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpftest.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpnormlim.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/mpnormtest.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/setfitparm.pro
@/home/fang/disk1/fang/IDL_sources/mpfit/tnmin.pro
